### ISSUE TITLE
Application initialization appears to be quadratic in the number of routes

### ISSUE THREAD

**Issue by jeremyevans** [rack-app/rack-app#2]
Rack::App appears to have O(1) routing, at least for static routes (as one would expect from using a hash table), but it also appears that application initialization is quadratic in the number of routes.  Here are rough times in seconds for initialization with the following number of routes:

```
10: 0.418303426
15: 0.419373569
100: 0.530071716
225: 0.936073043
1000: 10.068363325
3375: 110.984736365
```

Example code:

```
require 'rack/app'
class App < Rack::App
  1000.times do |i|
    get "/#{i.to_s}" do
    end
  end
end
```

Is this expected behavior?

**Comment by adamluzsi** [comment]
@jeremyevans yes, right now, we recompile endpoints when new middlewares or endpoints pushed to the application. The more endpoint given to a single application, the longer it takes to build the preconfigurated routing tree with rack apps. 

But this is better trade off than taking time in per requests, and because of this, we highly recommend to create isolated applications that have single purpose and not bigger, than what is  readable to the human eye. 
As how one of my friend told me: "A class should never bigger than my head..." :D :D :D 

With mounting you can mount as many sub applications to a main application as you want,
while your code is separated into different sub applications. 

This was a trade off, to make the application fully backward compatible, for those who use rolling release for they production applications, and to reduce to the minimum the "on request" processing requirements.

BTW, mr @jeremyevans I'm a terrible huge fan of your works, especially the sequel gem, which is my number one tool!!! Thank you for writing in my project! :)

**Comment by adamluzsi** [comment]
Can you tell me more about the use case you want to spike out ? :)

**Comment by jeremyevans** [comment]
I added support for benchmarking rack-app to https://github.com/jeremyevans/r10k.  Unfortunately, because application initialization is quadratic in rack-app, it comes in dead last for 10k routes if you consider both initialization and runtime.

Your benchmarks at https://github.com/rack-app/rack-app-benchmark must not include initialization time, otherwise I don't think rack-app would perform as well as indicated, unless the benchmarks were pretty long running.  BTW, my pull request for that repository hasn't been commented on yet. :)

I had a similar issue in Roda in regards to middleware, my solution was an extension that only compiled the application by method call, instead of on every middleware addition.  You may want to consider an optional extension that rack-app users could load that would not compile the routes on every route addition, only when a method is called.  That way, people with large numbers of routes could use rack-app without long initialization times.

**Comment by adamluzsi** [comment]
Oh my god, I should have read this before all the commits... Yes your suggestion is perfect, and during traveling home, I came up with the same idea, to recompile endpoints only when a new middleware definition given to the stack.

With this little optimization now it can work and I tested out with the r10k benchmark repository.

You are right I only measured the applications runtime, for the case when webserver initialized the workers and only have to receive and forward calls. 

I clean up my benchmark repository and add some case with this in mind in the future!
