### ISSUE TITLE
Selective Basic Auth

### ISSUE THREAD

**Issue by mimikadze** [rack-app/rack-app#24]
Hey, is there any convenient way to make selective Auth for certain endpoints?

I designed something like this:

```
class App < Rack::App
  
  def allowed_paths
    ['/v1/insecure_test', '/v1/other_insecure_endpoint']
  end

  def self.call(env)
    unless self.allowed_paths.include? env['REQUEST_PATH']
     middlewares do |b|
        b.use Rack::Auth::Basic, "Restricted Area" do |username, password|
          [username, password] == authenticate
        end
      end
      super
    else
      super
    end
  end

  namespace :v1 do
    get '/secure_test' do
      # some stuff that requires authentication
    end
   
    get '/insecure_test' do
      # some stuff that does't require authentication
    end
 end

end
```

But there's a drawback in this solution, it tries to authenticate any endpoint whether it was in `allowed_paths ` or not after you visit restricted URL. May be there is a common way for this functionality I have no idea of, or you can suggest some elegant one.

**Comment by adamluzsi** [comment]
Hello @mimikadze ,
first of all, thank you for using the framework!
It is a real honor to us, having you in the community! : )

By default there is no real convention in how to use the framework it self with selective auth logic,
but because you asked me, I happily share my experiences how we do at my company.

There is some useful thumb of rule that we follow:
* no monkey patch / overload
* try stick with [Screaming Architecture](https://8thlight.com/blog/uncle-bob/2011/09/30/Screaming-Architecture.html) if possible
  * Name your Application based on what it's purpose
* don't mutate application on runtime, prepend as much as possible
  * adding middlewares to the application based on if condition could and possibly lead to unexpected behaviors. 
    * if you need this and there is no cleaner solution, try stick with the rack interface and use a instance of the auth middleware with the self app as next callable, and simply call with the current env (but I don't recommend this fix because it will ads complexity to the next code reader)
* don't use REQUEST_PATH, because this env key implemented by handlers rather than the core tool set of the rack interface.
  * this mean webrick for example implement this, but If I remember well, unicorn or puma not, and you can receive unexpected results in production env.
* Try stick with the "single responsibility" ideology
  * each of your application should achieve one goal
    * one for example should take care of the authentication
    * one should proxy request to your business logic

I create an example repo for you to see some of this in action. 
These are not global rules, only rules that we like, and follow, but if you have different style, this doesn't mean our solution is better in any perspective, okey? :)

**Comment by adamluzsi** [comment]
I just finished create the example repo for you! :) 
[This is a simple example](https://github.com/rack-app/selective-auth-example) nothing hardcore. 
I tried to split responsibilities as much as I would always love too, and in the mean time, you just implicitly pointed out a technical dept, that I totally forgot already! 
To name, it was the middleware composition with mounting rack-app objects. 
Funny as is, rack compatible interface based apps already had this, so because we mainly used this selective auth logic to protect sidekiq web ui, there was no scenario where this tech dept could come out... So... You are awesome, even with asking you made a huge favor to me! 
Bump to the new version and you can have it's benefits too!

Hope the example repo will be useful to you! 
Say if you need anything : )

**Comment by adamluzsi** [comment]
Does the example answered in any way your question @mimikadze ?
Can I help you with anything else? :) 👍

**Comment by mimikadze** [comment]
Thanks for your detailed feedback and especially the demo app you've made for me. I got the concept and I'll try to stick to this approach in my apps with rack-app.

I appreciate you work much. I consider rack-app as a best alternative for "low-weight" API's instead of `rails new --api`. Will help your community if I have some ideas or input.

**Comment by adamluzsi** [comment]
Thank you so much, this really means a lot! : ))))
If you have any idea, or feeling that something should be done in a different way, feel free to share it!
