### ISSUE TITLE
[Question -- feature request?] Testing a rack-app with middlewares

### ISSUE THREAD

**Issue by qortex** [rack-app/rack-app#36]
I have this [SO Post](https://stackoverflow.com/questions/60976324/how-to-enable-middlewares-in-integration-tests-for-a-rack-app) looking like a tumbleweed. Was thinking this could be a good place to discuss that -- feel free to close if it's not the case.

What is the best way to RSpec-test a `rack-app` including the middlewares in the test?

Is there a command similar to `rack_app` for middlewares?

**Comment by adamluzsi** [comment]
Hi @qortex,

I'm not really active on stackoverflow, so I'm happy you opened this ticket here as well!

Is the logic in the middleware is a must requirement of a rack-app class?

If yes, then it should be used directly in the rack-app class, and it should be a simple spec as you would do normally. You define the rack-app subject with the `rack_app ClassNameHere` and do the testing. The Pro for this approach is that you don't have to know from the spec point of view, that some logic is in middlewares and some located in the controller part, as they are implementation details. As long the expected behavior is fulfilled in the spec test cases, it should be good.

But if the answer is no, then it should be tested independently and there should be one place where all the integrations usually are done. I usually do the composition of sub-rack-apps and middlewares in a top-level rack-app where I only use the `use` and the `mount` keywords and create an integration test to ensure routing and confirm the expected behavior of middlewares.

Is the logic in the middleware is a form of contract to the application, like the middleware ensure an value in the rack call env, but the value is not coupled with the middleware, then I would test the middleware on its own. And in the rack-app class spec, I would guarantee the entity in the rack call env. This will support the project's long-term maintenance aspects, and also makes the rack-app class easily reusable.

On the other hand, if you really need to test together but not use the middleware in the class directly then you can use the following idiom in the spec:
```
rack_app do
  use MiddlewareNameHere, params
  mount AppToTestWithTheMiddleware
end
```

Let me know what you think! : )

Cheers,
Adam

**Comment by adamluzsi** [comment]
Was I able to help you with this answer Michael (@qortex) ?

**Comment by qortex** [comment]
Hi @adamluzsi ,

Thanks for your detailed answer!
I didn't have time to test, but I think I understand why I am facing an issue.

I used middleware through `config.ru` so the middlewares are added to `rack` directly.

I think you suggest using `middlewares do` inside the `rack-app` (I didn't discover this command before my question), and I understand they would get incorporated to the `rack_app` in testing. Am I correct?

I will test to see if that's indeed the case. Then I could contribute an example if you think it's worth it.

**Comment by adamluzsi** [comment]
Hi @qortex ,

yes, you are correct. 
There is two way to achieve your goal, the first is when you use a rack-app class instead of the config.ru and do the composition of the web application there. In this case the `rack_app BaseAppClassName` setup would use an application which already has the middlewares.

If you want to stick with the config.ru setup, then all you need to do is to use the rack_app spec helper function with block syntax, and mount your app to the root and use the middlewares you want there just like in the `config.ru` file.

Using the rack_app spec helper with block will create a anonymous class instance where the class definition is the same as the block content, so you can mimic the content of the config.ru there with that.

If you want to see an example on how to use the middlewares block, please check out the following link:
http://www.rack-app.com/examples/middleware
http://www.rack-app.com/examples/next_endpoint_middlewares

I tried to put some example on the website, hope some of them might help someone.

J'espère que je vous ai aidé.

Cheers,
Adam

**Comment by adamluzsi** [comment]
@qortex , did you had any luck on progressing with your issue?

**Comment by qortex** [comment]
Hi,
sorry, was working on something else and didn't progress on this.
I will note that closed since it's not an open issue :)

**Comment by adamluzsi** [comment]
sure @qortex. If you need help, feel free to write or open an issue and tag me! : )
