### ISSUE TITLE
Rack::App::FileServer.serve_file gives Errno::EPERM when file served from a shared folder where multiple user keep files like the temp directory.

### ISSUE THREAD

**Issue by crux** [rack-app/rack-app#41]
Calling `#serve_file` to with a generated tempfile might fail with a permission error when not all files in the temp directory are readable.

[2020-12-12 13:08:38] ERROR Errno::EPERM: Operation not permitted - /var/folders/p5/bjvqf64509z5k5kyhkmyknch0000gn/T/com.apple.iCal/TemporaryItems

The temp file in case was: 
/var/folders/p5/bjvqf64509z5k5kyhkmyknch0000gn/T/points20201212-56050-1p0873w.csv

**Reproduce:**

```
tmp = Tempfile.new(%w[points .csv])
puts ">>> #{tmp.path} <<<"

# having or creating any non readable file/dir in the /var/folders/p5/bjvqf64509z5k5kyhkmyknch0000gn/T directory now will fail the serve_file call
# I'm to lazy now, in my case it was a calendar file showing up there,

serve_file tmp.path
```

The reason for this is that serve_file starts a file server for ALL files in the directory of the given path. With resulting eperm in case any non readable file is there. 

Besides that, this also is a security bug, exposing the whole directory instead of just the file.

You can read the globbing action in file_server.rb:6:

```
[2020-12-12 13:08:38] ERROR Errno::EPERM: Operation not permitted - /var/folders/p5/bjvqf64509z5k5kyhkmyknch0000gn/T/com.apple.iCal/TemporaryItems
        /Users/crux/.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/file_server.rb:6:in `glob'
        /Users/crux/.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/file_server.rb:6:in `initialize'
        /Users/crux/.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/file_server.rb:24:in `new'
        /Users/crux/.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/file_server.rb:24:in `serve_file'
        /Users/crux/.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/instance_methods/upload.rb:4:in `serve_file'
```

**ruby version**
**rack-app version**
```
.rvm/gems/ruby-2.7.1/gems/rack-app-4.0.1/lib/rack/app/file_server.rb
```

**Comment by adamluzsi** [comment]
Hello @crux ,

Thank you so much for submitting this issue!
Sorry for the late answer, I'm on vacation at the moment, but I make sure to allocate time for your request and solve it as soon as possible!

I'm really pleased with your issue's detailed  description, it will help me for sure to extend the specification of serve_file with this edge case.

Cheers
Adam

**Comment by adamluzsi** [comment]
I found the situation Interesting. 

`rack-app` provides syntax sugar to `rack/file`'s `serve_file` (`Rack::App::FileServer.serve_file`).
The implementation seems to make a file server using the file path directory, then attempt to serve the given file.
This causes an issue if the served file is mixed with non-project related files.

I see two possible workarounds for now.
- rack-app handle Errno::EPERM error during serve_file and make a temp directory which has a single link entry to the file and reattempt to serve the file with the link
- use a dedicated temp directory for the project instead of the global Temp.

For now, I extend the project specification with the following case:
given there is a directory
when two file present
one doesn't allow access/read
another file is readable
and this another file is requested and then served back.

From a security point of view, the use of serve_file should be handled similarly to the `rack/file` `serve_file`.

Would that be okay with you if I solely focus on handling the error,
and you check if it is possible to use a dedicated temporally folder for your project?

**Comment by adamluzsi** [comment]
It's a bit awkward, but I just realised that I couldn't recreate this edge case in a test with a real-world behavioural test without a multi-user setup and root access.

Initially, I thought it is possible to recreate this edge case by setting the file mode to `0` (`-rwx`).
This error only seems to be raised in a multi-user shared folder setup.

This at least sorts out the security concern, since, at the OS level, 
the system will forbid any access to a file that belongs to someone else 
if the file mod/group, of course, don't permit the action.

I'm not particularly eager to use stubs, but OS-related behaviours can be considered non-volatile/stable so it should be okay.

**Comment by adamluzsi** [comment]
Handling this in the `rack-app` project feels out of place, the more stubbed test I write.
In practice, this seems like an issue with how the `rack` project does the single file serving under the hood.

I see the following possible approaches for now:
- we do a pair programming session and create a PR for the `rack` project, where we remove the `glob` usage from the single `serve_file` code path two option for us again
- An issue will be opened for the `rack` project to bring awareness to this with their `serve_file` method call.

Would you be okay to propose this change request to the [`rack` project](http://github.com/rack/rack) itself or do you prefer the pair programming session with me to create a solution for the rack project to exclude glob from `serve_file` in `rack/file`?

After a new `rack` release with the fixed `serve_file`, all you have to do to update `rack` in your `Gemfile`,
and `rack-app` will use the new logic out of the box.

In the meantime, I try to think about other possible non-hacky solutions as well.
I would like to avoid implementing and maintaining a custom file server solution in rack-app.
I'm sorry that I was not much of a help, for now, I really try to think about a win-win solution for both of us.

Cheers
Adam

**Comment by adamluzsi** [comment]
I should not work at 2 o'clock.

**Comment by adamluzsi** [comment]
@crux can you give it a try and update to the latest version?
> gem 'rack-app', '~> 7.7'

The issue should be fixed with this version, please give it a try and let me know if it works as you expected.

Cheers,
Adam

**Comment by adamluzsi** [comment]
@crux, happy new year to you!
Did you had the chance to try out the latest version?

**Comment by adamluzsi** [comment]
@crux I close this issue if that's okay for you.
The reported bug was proven with a test and I released a fixed version,

Cheers and Happy coding! : )

**Comment by crux** [comment]
dear adam, I am perfectly fine with it. I never could follow-up on this, I
moved on, had to work around it differently and could never slot the time
to properly validate and help you with your fix. The more I m happy I could
be off help to improve things a bit with my report. Thanks a lot for taking
care of this and good luck further,

dirk

**Comment by adamluzsi** [comment]
Dear @crux,

Your report was a great help, and please don't hesitate to report issues in the future; it is more than welcome!
It was unfortunate that I was on vacation during the time you opened the issue.

Cheers, and I wish you all the best!
Adam L.
